"""Add payment_method, price, weight to buy_items

Revision ID: ae6c2bdb2564
Revises: b810ceccf6ca
Create Date: 2025-05-21 18:00:52.351172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6c2bdb2564'
down_revision = 'b810ceccf6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_items', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('buy_items', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('buy_items', sa.Column('weight', sa.Float(), nullable=False))
    op.alter_column('buy_items', 'buyer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buy_items', 'buyer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('buy_items', 'weight')
    op.drop_column('buy_items', 'price')
    op.drop_column('buy_items', 'payment_method')
    # ### end Alembic commands ###
